// short name
const SHORT_NAME_ETHEREUM = "eth";
const SHORT_NAME_GOERLI = "gor";
const SHORT_NAME_SEPOLIA = "sep";
const SHORT_NAME_OPTIMISTIC = "oeth";
const SHORT_NAME_ARBITRUM = "arb1";
const SHORT_NAME_OPTIMISTIC_GOERLI = "ogor";
const SHORT_NAME_ARBITRUM_GOERLI = "arb-goerli";
const SHORT_NAME_EVMOS = "evmos";
const SHORT_NAME_EVMOS_TEST = "evmos-testnet";
const SHORT_NAME_ARBITRUM_NOVA = "arb-nova";
const SHORT_NAME_BINANCE = "bnb";
const SHORT_NAME_BINANCE_TEST = "bnbt";
const SHORT_NAME_AVALANCHE = "avax";
const SHORT_NAME_AVALANCHE_TEST = "fuji";
const SHORT_NAME_FANTOM = "ftm";
const SHORT_NAME_FANTOM_TEST = "tftm";
const SHORT_NAME_HARMONY = "hmy-s0";
const SHORT_NAME_HARMONY_TEST = "hmy-b-s0";
const SHORT_NAME_POLYGON = "matic";
const SHORT_NAME_POLYGON_MUMBAI = "maticmum";
const SHORT_NAME_POLYGON_ZKEVM_TEST = "zkevmtest";
const SHORT_NAME_QUARKCHAIN = "qkc-s0";
const SHORT_NAME_QUARKCHAIN_DEVNET = "qkc-d-s0";
const SHORT_NAME_QUARKCHAIN_L2_TESTNET = "qkcl2-b";
// ethstorage
const SHORT_NAME_ETHSTORAGE_MAINNET = "es-m";
const SHORT_NAME_ETHSTORAGE_SEPOLIA = "es-t";
const SHORT_NAME_ETHSTORAGE_L2_BETA = "es-d";

// chain id
const ETHEREUM_CHAIN_ID = 1;
const GOERLI_CHAIN_ID = 5;
const SEPOLIA_CHAIN_ID = 11155111;
const OPTIMISTIC_CHAIN_ID = 10;
const ARBITRUM_CHAIN_ID = 42161;
const OPTIMISTIC_GOERLI_CHAIN_ID = 420;
const ARBITRUM_GOERLI_CHAIN_ID = 421613;
const EVMOS_CHAIN_ID = 9001;
const EVMOS_TEST_CHAIN_ID = 9000;
const ARBITRUM_NOVA_CHAIN_ID = 42170;
const BINANCE_CHAIN_ID = 56;
const BINANCE_TEST_CHAIN_ID = 97;
const AVALANCHE_CHAIN_ID = 43114;
const AVALANCHE_TEST_CHAIN_ID = 43113;
const FANTOM_CHAIN_ID = 250;
const FANTOM_TEST_CHAIN_ID = 4002;
const HARMONY_CHAIN_ID = 1666600000;
const HARMONY_TEST_CHAIN_ID = 1666700000;
const POLYGON_CHAIN_ID = 137;
const POLYGON_MUMBAI_CHAIN_ID = 80001;
const POLYGON_ZKEVM_TEST_CHAIN_ID = 1402;
const QUARKCHAIN_CHAIN_ID = 100001;
const QUARKCHAIN_DEVNET_CHAIN_ID = 110001;
const QUARKCHAIN_L2_TESTNET_CHAIN_ID = 3335;

const NETWORK_MAPPING = {
    [SHORT_NAME_ETHEREUM]: ETHEREUM_CHAIN_ID,
    [SHORT_NAME_GOERLI]: GOERLI_CHAIN_ID,
    [SHORT_NAME_SEPOLIA]: SEPOLIA_CHAIN_ID,
    [SHORT_NAME_OPTIMISTIC]: OPTIMISTIC_CHAIN_ID,
    [SHORT_NAME_ARBITRUM]: ARBITRUM_CHAIN_ID,
    [SHORT_NAME_OPTIMISTIC_GOERLI]: OPTIMISTIC_GOERLI_CHAIN_ID,
    [SHORT_NAME_ARBITRUM_GOERLI]: ARBITRUM_GOERLI_CHAIN_ID,
    [SHORT_NAME_EVMOS]: EVMOS_CHAIN_ID,
    [SHORT_NAME_EVMOS_TEST]: EVMOS_TEST_CHAIN_ID,
    [SHORT_NAME_ARBITRUM_NOVA]: ARBITRUM_NOVA_CHAIN_ID,
    [SHORT_NAME_BINANCE]: BINANCE_CHAIN_ID,
    [SHORT_NAME_BINANCE_TEST]: BINANCE_TEST_CHAIN_ID,
    [SHORT_NAME_AVALANCHE]: AVALANCHE_CHAIN_ID,
    [SHORT_NAME_AVALANCHE_TEST]: AVALANCHE_TEST_CHAIN_ID,
    [SHORT_NAME_FANTOM]: FANTOM_CHAIN_ID,
    [SHORT_NAME_FANTOM_TEST]: FANTOM_TEST_CHAIN_ID,
    [SHORT_NAME_HARMONY]: HARMONY_CHAIN_ID,
    [SHORT_NAME_HARMONY_TEST]: HARMONY_TEST_CHAIN_ID,
    [SHORT_NAME_POLYGON]: POLYGON_CHAIN_ID,
    [SHORT_NAME_POLYGON_MUMBAI]: POLYGON_MUMBAI_CHAIN_ID,
    [SHORT_NAME_POLYGON_ZKEVM_TEST]: POLYGON_ZKEVM_TEST_CHAIN_ID,
    [SHORT_NAME_QUARKCHAIN]: QUARKCHAIN_CHAIN_ID,
    [SHORT_NAME_QUARKCHAIN_DEVNET]: QUARKCHAIN_DEVNET_CHAIN_ID,
    [SHORT_NAME_QUARKCHAIN_L2_TESTNET]: QUARKCHAIN_L2_TESTNET_CHAIN_ID,
}

const ETH_STORAGE_NETWORK_MAPPING = {
    [SHORT_NAME_ETHSTORAGE_MAINNET]: ETHEREUM_CHAIN_ID,
    [SHORT_NAME_ETHSTORAGE_SEPOLIA]: SEPOLIA_CHAIN_ID,
    [SHORT_NAME_ETHSTORAGE_L2_BETA]: QUARKCHAIN_L2_TESTNET_CHAIN_ID,
}

const PROVIDER_URLS = {
    [GOERLI_CHAIN_ID]: 'https://rpc.ankr.com/eth_goerli',
    [SEPOLIA_CHAIN_ID]: 'http://65.108.230.142:8545/',
    [OPTIMISTIC_CHAIN_ID]: 'https://mainnet.optimism.io',
    [ARBITRUM_CHAIN_ID]: 'https://arb1.arbitrum.io/rpc',
    [OPTIMISTIC_GOERLI_CHAIN_ID]: 'https://goerli.optimism.io',
    [ARBITRUM_GOERLI_CHAIN_ID]: 'https://goerli-rollup.arbitrum.io/rpc',
    [EVMOS_CHAIN_ID]: 'https://evmos-evm.publicnode.com',
    [EVMOS_TEST_CHAIN_ID]: 'https://eth.bd.evmos.dev:8545',
    [ARBITRUM_NOVA_CHAIN_ID]: 'https://nova.arbitrum.io/rpc',
    [BINANCE_CHAIN_ID]: 'https://bsc-dataseed2.binance.org',
    [BINANCE_TEST_CHAIN_ID]: 'https://data-seed-prebsc-1-s1.binance.org:8545',
    [AVALANCHE_CHAIN_ID]: 'https://api.avax.network/ext/bc/C/rpc',
    [AVALANCHE_TEST_CHAIN_ID]: 'https://avalanchetestapi.terminet.io/ext/bc/C/rpc',
    [FANTOM_CHAIN_ID]: 'https://rpcapi.fantom.network',
    [FANTOM_TEST_CHAIN_ID]: 'https://rpc.testnet.fantom.network',
    [HARMONY_CHAIN_ID]: 'https://a.api.s0.t.hmny.io',
    [HARMONY_TEST_CHAIN_ID]: 'https://api.s0.b.hmny.io',
    [POLYGON_CHAIN_ID]: 'https://polygon-rpc.com',
    [POLYGON_MUMBAI_CHAIN_ID]: 'https://matic-mumbai.chainstacklabs.com',
    [POLYGON_ZKEVM_TEST_CHAIN_ID]: 'https://rpc.public.zkevm-test.net',
    [QUARKCHAIN_CHAIN_ID]: 'https://mainnet-s0-ethapi.quarkchain.io',
    [QUARKCHAIN_DEVNET_CHAIN_ID]: 'https://devnet-s0-ethapi.quarkchain.io',
    [QUARKCHAIN_L2_TESTNET_CHAIN_ID]: 'https://rpc.beta.testnet.l2.quarkchain.io:8545',
}

const NS_ADDRESS = {
    [ETHEREUM_CHAIN_ID]: '0x00000000000c2e074ec69a0dfb2997ba6c7d2e1e',
    [SEPOLIA_CHAIN_ID]: '0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e',
}

const ETH_STORAGE_RPC = {
    [ETHEREUM_CHAIN_ID]: 'https://rpc.mainnet.ethstorage.io:9545',
    [SEPOLIA_CHAIN_ID]: 'https://rpc.testnet.ethstorage.io:9546',
    [QUARKCHAIN_L2_TESTNET_CHAIN_ID]: 'https://rpc.beta.testnet.l2.ethstorage.io:9596',
}

const TYPE_CALLDATA = 'calldata';
const TYPE_BLOB = 'blob';

const DEFAULT_THREAD_POOL_SIZE_ONE = 1;
const DEFAULT_THREAD_POOL_SIZE_LOW = 6;
const DEFAULT_THREAD_POOL_SIZE_HIGH = 15;

module.exports = {
    NETWORK_MAPPING,
    PROVIDER_URLS,
    NS_ADDRESS,
    ETH_STORAGE_RPC,
    ETH_STORAGE_NETWORK_MAPPING,

    ARBITRUM_NOVA_CHAIN_ID,
    ETHEREUM_CHAIN_ID,
    SEPOLIA_CHAIN_ID,
    QUARKCHAIN_L2_TESTNET_CHAIN_ID,

    TYPE_CALLDATA,
    TYPE_BLOB,

    DEFAULT_THREAD_POOL_SIZE_ONE,
    DEFAULT_THREAD_POOL_SIZE_LOW,
    DEFAULT_THREAD_POOL_SIZE_HIGH
}
